<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXuxjiYA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXuxjiYA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXuxjiYA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXuxjiYA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXuxjiYA\App_KernelDevDebugContainer([
    'container.build_hash' => 'XuxjiYA',
    'container.build_id' => '00a4f65c',
    'container.build_time' => 1723834081,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXuxjiYA');
